# Basic simulation for DART version 5.6.0

# Global settings ######################################################################################################

dart_path =   'dart'                               # put here your DART executable (version 5.6.0 executable)
version = '5.6.0'                       # make sure you really know what we are talking about

simulation_name = "default560_simulation"
simulation_location = 'location'

output_location ='output'


# Preprocessing ########################################################################################################

## Geometry / coordinates
#[geometry]
#epsg = 4326
#ROI = [-20, 20, -20, 20]    # left, right, bottom, top


# Simulation ###########################################################################################################
[run_parameters]
    numberOfIterations = 5
    extrapolation = 1
    nbThreads = 4

    albedoThreshold = 1e-5
    lightPropagationThreshold = 1e-5
    nbSubcenterIllumination = 10

    isAPEX = 0                  # flag to use the APEX band definition or a user defined band
    onlyUse1GroundOP = true     # flag to set, if only one ground optical property should be used in order to have one homogenous
                                # ground spectrum. This flag actually accomplishes, that we do not add voxels on top of the terrain.
                                # Instead we add a GOP to the terrain (unfortunately you can only assign one GOP per terrain).

    ## LOPs
    isLOPEXlops = true
    isLOPEX_multipleLOPS = false    # IMPORTANT: set this flag to false if you want to simulate with measured LOPS!!!


## Phase
[phase]
    deltaLambda = 0.01
    meanLambda = 0.68
    bandNumber = 1
    bandNumbers = 0
    isMultipleBandsInSimulation = false # true if arrays were defined for meanLambda, deltaLambda and bandNumber


    ## Product specifications
    [phase.products]
        order1Products = 0
        brfProducts = 1
        brfProduct = 1
        horizontalOversampling = 1
        image = 1
        luminanceProducts = 1
        maximalThetaImages = 0.1
        nb_scene = 1
        projection = 1


    [phase.sensor]
        sensorOversampling = 1
        sensorPlaneprojection = 1
        allIterationsProducts = 1


## Directions
[directions]
    sunViewingAzimuthAngle = 90
    sunViewingZenithAngle = 45
    numberOfPropagationDirections = 10

    oversampleDownwardRegion = 1
    numberOfDownwardDirections = 10
    omegaDown = 0.1

    oversampleUpwardRegion = 1
    numberOfUpwardDirections = 10
    omegaUp = 0.1


## Maket
[maket]
    voxelDim = [0.25, 0.25, 0.25] # dx, dy, dz

# atmosphere
[atmosphere]
    [atmosphere.general]
        isRadiativeTransfertInBottomAtmosphereDefined = 0
        typeOfAtmosphere = 0
        #atmosphereIterations =

        writeTransferFunctions = 0                   # write transfer function (reusable by dart)
        inputOutputTransfertFunctions = 0

    [atmosphere.products]
        atmosphereBRF_TOA = 0
        atmosphereRadiance_BOA_before_coupling = 0
        atmosphereRadiance_BOA_after_coupling = 0
        order_1 = 0

    [atmosphere.components]
        downwardingFluxes = 0
        upwardingFluxes = 0

    [atmosphere.expert]
        seuilEclairementAtmos = 1e-5
        seuilFTAtmos = 1e-4
        extrapol_atmos = 0

    [atmosphere.geometry]
        discretisationAtmos = 0
        heightOfSensor = 10000
        minimumNumberOfDivisions = 2

    [atmosphere.dimensions]
        xAI = 100
        yAI = 100
        zAI = 500
        hCFAI = 4000    # height midatmosphere
        hCFHA = 80000   # height upper atmosphere
        zHA = 2000
#        BA_altitude =

    [atmosphere.water]
            include = 1
            precipitableWaterAmount = 1.0

    # if working with a database -> typeOfAtmosphere = 0
    [atmosphere.optical_property_db]
        temperatureModelName = "MIDLATSUM"
        correctionBandModel = 1
        dataBaseName = "dart_atmosphere.db"


        [atmosphere.optical_property_db.gas]
            group = 1
            modelName = "MIDLATSUM"                 # gas optical properties
            cumulativeModelName = "MIDLATSUM"
            gasParametersModelName = "USSTD76"

        [atmosphere.optical_property_db.aerosol]
             cumulativeModelName = "RURALV23"       # aerosol vertical profile
             optDepthFactor = 1                     # aerosol optical depth factor
             group = 1                              # same model for all parameters
             modelName = "RURALV23"                 # aerosol optical properties
             hgParametersModelName = "RURALV23"     # aerosol Henyey Greenstein Parameters

    # using monospectral -> type_of_atmosphere = 1
    [atmosphere.optical_property]
        temperature_file_name = "atmosphereTemperature.txt"     # aerosol Henyey Greenstein Parameters
        correct_mid_point = 1
        correct_earth_curvature = 1
        
        heyney_greenstein_a = 0.95
        heyney_greenstein_g1 = 0.79
        heyney_greenstein_g2 = 0.4

        [atmosphere.optical_property.gas]
            scale_factor = 8400
            optical_depth = 0.049
            transmittance = 0.75                     
             
        [atmosphere.optical_property.aerosol]
             scale_factor = 1000
             optical_depth = 0.202
             albedo = 0.947

        
## object3d
[object3d]
    importObject3d = true
    path2obj = "3D_Objects/Bubikon_StemObject_ModeledInMeshlab_swapYZ_0atMinCorner.obj"
    location = [0, 0]                           # x, y
    objPosFile = "~/dart_565_run/Bubikon_Datasets/StemLocation_XY_recentered.txt"
    dim = [0, 0, 0]                             # x, y, z, Caution: Hardcoded!
                                                # TODO: Find a way to extract dimensions from the object directly.

        [object3d.op]
            type = 0
            indexFctPhase = 2
            modelName = 'bark_decidous'

        [object3d.tp]
            idTemperature = 'thermal_function_290_310'
            indexTemp = 0


# Postprocessing #######################################################################################################

[postprocessing]

########################################################################################################################