# Basic simulation for DART version 5.6.0

# Global settings ######################################################################################################

dart_path =   'dart'                               # put here your DART executable (version 5.6.0 executable)
dart_version = '5.6.0'                       # make sure you really know what we are talking about

simulation_name = "default560_simulation"
simulation_location = 'location'

output_location ='output'


# Preprocessing ########################################################################################################

## Geometry / coordinates
#[geometry]
#epsg = 4326
#ROI = [-20, 20, -20, 20]    # left, right, bottom, top


# Simulation ###########################################################################################################
[run_parameters]
    numberOfIterations = 5
    extrapolation = 1
    nbThreads = 4

    albedoThreshold = 1e-5
    lightPropagationThreshold = 1e-5
    nbSubcenterIllumination = 10

    isAPEX = 0                  # flag to use the APEX band definition or a user defined band
    onlyUse1GroundOP = true     # flag to set, if only one ground optical property should be used in order to have one homogenous
                                # ground spectrum. This flag actually accomplishes, that we do not add voxels on top of the terrain.
                                # Instead we add a GOP to the terrain (unfortunately you can only assign one GOP per terrain).

    ## LOPs
    isLOPEXlops = true
    isLOPEX_multipleLOPS = false    # IMPORTANT: set this flag to false if you want to simulate with measured LOPS!!!


## Phase
[phase]
    deltaLambda = 0.01
    meanLambda = 0.68
    bandNumber = 1
    bandNumbers = 0
    isMultipleBandsInSimulation = false # true if arrays were defined for meanLambda, deltaLambda and bandNumber


    ## Product specifications
    [phase.products]
        order1Products = 0
        brfProducts = 1
        brfProduct = 1
        horizontalOversampling = 1
        image = 1
        luminanceProducts = 1
        maximalThetaImages = 0.1
        nb_scene = 1
        projection = 1


    [phase.sensor]
        sensorOversampling = 1
        sensorPlaneprojection = 1
        allIterationsProducts = 1


## Directions
[directions]
    sunViewingAzimuthAngle = 90
    sunViewingZenithAngle = 45
    numberOfPropagationDirections = 10

    oversampleDownwardRegion = 1
    numberOfDownwardDirections = 10
    omegaDown = 0.1

    oversampleUpwardRegion = 1
    numberOfUpwardDirections = 10
    omegaUp = 0.1


## Maket
[maket]
    voxelDim = [0.25, 0.25, 0.25] # dx, dy, dz

# atmosphere
[atmosphere]
    [atmosphere.general]
        isRadiativeTransfertInBottomAtmosphereDefined = 0
        #typeOfAtmosphere =

        #atmosphereIterations =
        dataBaseName = "dart_atmosphere.db"
        correctionBandModel = 1

        writeTransferFunctions = 0                   # write transfer function (reusable by dart)
        #inputOutputTransfertFunctions =

        atmosphereBRF_TOA = 0
        atmosphereRadiance_BOA_apres_couplage = 0
        atmosphereRadiance_BOA_avantCouplage = 0
        ordreUnAtmos = 0

#        downwardingFluxes =
#        upwardingFluxes =
#        extrapol_atmos =
#        seuilEclairementAtmos =
#        seuilFTAtmos =

    [atmosphere.geometry]
#        discretisationAtmos =
#        heightOfSensor =
#        minimumNumberOfDivisions =

    [atmosphere.dimensions]
#        xAI =
#        yAI =
#        zAI =
#        hCFAI = # height
#        hCFHA =
#        zHA =
#        BA_altitude =

    [atmosphere.optical_property]
        hgParametersModelName = "RURALV23"     # aerosol Henyey Greenstein Parameters
        temperatureModelName = "MIDLATSUM"

        [atmosphere.optical_property.water]
            precipitableWaterAmountCheckbox = 1
#            precipitableWaterAmount =

        [atmosphere.optical_property.gas]
            group = 1
            modelName = "MIDLATSUM"                 # gas optical properties
            cumulativeModelName = "MIDLATSUM"

        [atmosphere.optical_property.aerosol]
             cumulativeModelName = "RURALV23"       # aerosol vertical profile
             optDepthFactor = 1                     # aerosol optical depth factor
             group = 1                              # same model for all parameters
             modelName = "RURALV23"                 # aerosol optical properties
#             gasCumulativeModelName =
#             parametersModelName =

## object3d
[object3d]
    importObject3d = true
    path2obj = "3D_Objects/Bubikon_StemObject_ModeledInMeshlab_swapYZ_0atMinCorner.obj"
    location = [0, 0]                           # x, y
    objPosFile = "~/dart_565_run/Bubikon_Datasets/StemLocation_XY_recentered.txt"
    dim = [0, 0, 0]                             # x, y, z, Caution: Hardcoded!
                                                # TODO: Find a way to extract dimensions from the object directly.

        [object3d.op]
            type = 0
            indexFctPhase = 2
            modelName = 'bark_decidous'

        [object3d.tp]
            idTemperature = 'thermal_function_290_310'
            indexTemp = 0


# Postprocessing #######################################################################################################

[postprocessing]

########################################################################################################################